# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: history.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rhistory.proto\"\x18\n\x07Request\x12\r\n\x05value\x18\x01 \x01(\t\"\x9e\x03\n\x0eTickerResponse\x12!\n\x19stock_price_historical_id\x18\x01 \x01(\x05\x12\"\n\x1ahistorical_price_date_time\x18\x02 \x01(\t\x12\x16\n\x0e\x64\x61y_open_price\x18\x03 \x01(\x01\x12\x16\n\x0e\x64\x61y_high_price\x18\x04 \x01(\x01\x12\x15\n\rday_low_price\x18\x05 \x01(\x01\x12\x17\n\x0f\x64\x61y_close_price\x18\x06 \x01(\x01\x12\x12\n\nday_volume\x18\x07 \x01(\x01\x12\x11\n\tticker_id\x18\x08 \x01(\t\x12\r\n\x05\x62u_id\x18\t \x01(\x05\x12\x11\n\tsub_bu_id\x18\n \x01(\x05\x12\x16\n\x0e\x61pplication_id\x18\x0b \x01(\x05\x12\x11\n\tis_active\x18\x0c \x01(\x08\x12\x12\n\ncreated_by\x18\r \x01(\x05\x12\x14\n\x0c\x63reated_date\x18\x0e \x01(\t\x12\x18\n\x10last_modified_by\x18\x0f \x01(\x05\x12\x1a\n\x12last_modified_date\x18\x10 \x01(\t\x12\x11\n\tisin_code\x18\x11 \x01(\t\"4\n\x0fTickerResponses\x12!\n\x08response\x18\x01 \x03(\x0b\x32\x0f.TickerResponse2V\n\x07history\x12&\n\x06GetAll\x12\x08.Request\x1a\x10.TickerResponses\"\x00\x12#\n\x03Get\x12\x08.Request\x1a\x10.TickerResponses\"\x00\x62\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_TICKERRESPONSE = DESCRIPTOR.message_types_by_name['TickerResponse']
_TICKERRESPONSES = DESCRIPTOR.message_types_by_name['TickerResponses']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'history_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

TickerResponse = _reflection.GeneratedProtocolMessageType('TickerResponse', (_message.Message,), {
  'DESCRIPTOR' : _TICKERRESPONSE,
  '__module__' : 'history_pb2'
  # @@protoc_insertion_point(class_scope:TickerResponse)
  })
_sym_db.RegisterMessage(TickerResponse)

TickerResponses = _reflection.GeneratedProtocolMessageType('TickerResponses', (_message.Message,), {
  'DESCRIPTOR' : _TICKERRESPONSES,
  '__module__' : 'history_pb2'
  # @@protoc_insertion_point(class_scope:TickerResponses)
  })
_sym_db.RegisterMessage(TickerResponses)

_HISTORY = DESCRIPTOR.services_by_name['history']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=17
  _REQUEST._serialized_end=41
  _TICKERRESPONSE._serialized_start=44
  _TICKERRESPONSE._serialized_end=458
  _TICKERRESPONSES._serialized_start=460
  _TICKERRESPONSES._serialized_end=512
  _HISTORY._serialized_start=514
  _HISTORY._serialized_end=600
# @@protoc_insertion_point(module_scope)
